### PR TITLE
Declarative approach to implement API calls

### PR DESCRIPTION
**Pull request by fogfish**
__WHAT__

1. Interfaces

SDK defines interface for core concepts 
* `oauth.Provider`
* `api.Connetor`

Interfaces helps to mock and test SDK implementation

2. Declarative HTTP I/O

The proposal is inspired by my declarative HTTP libraries

```
api.Connector -[ creates ]-> *CURL

CURL implements
func (curl *CURL) Send(data interface{}) *CURL
func (curl *CURL) Recv(data interface{}) error
func (curl *CURL) RecvStatus() error
```

Example of usage

```
err = vault.api.
  Get("/vault/api/v1/secrets/%s", url.PathEscape(name)).
  Recv(&bag)
```

3. Unit testing for client 
 

__NOTE__

* api.Client requires a lot of refactoring but it happens in future PR. We need to unlock boilerplate less api development asap.
* We need to agree about type-safe approach across api methods but it happens in later as well

### CODE REVIEW

**Comment by fogfish** [comment]
@markkurossi @jukeks Gentlemen, please review the proposal. I've completed with the concept and base things are defined. Let's polish it and merge so that development is unblocked.

**Comment by markkurossi** [comment]
The changes look very clean!

**Comment by fogfish** [comment]
Just notice a bug at `.github/workflows/go.yml`. It was always using master branch of the repo for PR testing 😮 . Which make no sense. It took me awhile to fix. Once, this PR is merge the actions would tests proposed code.

**Comment by markkurossi** [comment]
I noticed the same thing earlier, the checkout action checks the branch out in some weird "detached head" state, and in my example new files where not in the build environment. Couldn't really figure out how to fix that.

**Pull request merged**
